{{- if .Values.federation.ingress.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spire-server.fullname" . }}-federation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.federation.ingress.certIssuer | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    {{- with .Values.federation.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.federation.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.federation.ingress.host | quote }}
      secretName: {{ include "spire-server.fullname" . }}-federation-tls
  rules:
    - host: {{ .Values.federation.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spire-server.fullname" . }}
                port:
                  name: federation
{{- end }}
