apiVersion: v1
kind: ConfigMap
metadata:
  name: "postgres-monitoring-queries"
  namespace: {{ .Values.postgresHa.namespace | quote }}
  labels:
    kacho.cloud/component: postgres-monitoring
data:
  queries.yaml: |
    pg_stat_replication:
      query: |
        SELECT
          application_name,
          state,
          sync_state,
          (pg_wal_lsn_diff(pg_current_wal_lsn(), sent_lsn))::bigint  AS sent_diff_bytes,
          (pg_wal_lsn_diff(pg_current_wal_lsn(), write_lsn))::bigint AS write_diff_bytes,
          (pg_wal_lsn_diff(pg_current_wal_lsn(), flush_lsn))::bigint AS flush_diff_bytes,
          (pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn))::bigint AS replay_diff_bytes
        FROM pg_stat_replication;
      metrics:
        - application_name:
            usage: "LABEL"
            description: "Standby application name"
        - state:
            usage: "LABEL"
        - sync_state:
            usage: "LABEL"
        - sent_diff_bytes:
            usage: "GAUGE"
            description: "Bytes between current WAL LSN and sent LSN"
        - flush_diff_bytes:
            usage: "GAUGE"
        - replay_diff_bytes:
            usage: "GAUGE"
