{{- if .Values.certManager.issuers.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuers.staging.name | quote }}
  labels:
    kacho.cloud/component: cert-manager
    app.kubernetes.io/managed-by: helm
spec:
  acme:
    server: {{ .Values.certManager.issuers.staging.server | quote }}
    email: {{ .Values.certManager.acmeEmail | quote }}
    privateKeySecretRef:
      name: "letsencrypt-staging-account-key"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.certManager.cloudflare.apiTokenSecret.name | quote }}
              key: {{ .Values.certManager.cloudflare.apiTokenSecret.key | quote }}
        selector:
          dnsZones:
            {{- range .Values.certManager.dnsZones }}
            - {{ tpl . $ | quote }}
            {{- end }}
{{- end }}
