apiVersion: v1
kind: Service
metadata:
  name: {{ include "kacho-iam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kacho-iam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.public.type }}
  selector:
    {{- include "kacho-iam.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.public.port }}
      targetPort: grpc
