{{- if .Values.cloudflare.crossplane.enabled }}
{{- range .Values.cloudflare.dns.records }}
---
apiVersion: cloudflare.crossplane.io/v1alpha1
kind: Record
metadata:
  name: {{ printf "dns-%s" (.name | lower | replace "@" "apex" | replace "." "-") | quote }}
  labels:
    kacho.cloud/component: cloudflare-dns
spec:
  forProvider:
    zone: {{ $.Values.cloudflare.zone | quote }}
    name: {{ tpl .name $ | quote }}
    type: {{ .type | quote }}
    value: {{ tpl .content $ | quote }}
    proxied: {{ .proxied }}
    ttl: {{ .ttl }}
  providerConfigRef:
    name: cloudflare-default
{{- end }}
{{- end }}
