{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spiffe-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiffe-csi.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spiffe-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiffe-csi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spiffe-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spiffe-csi.selectorLabels" . | nindent 8 }}
        {{- include "spiffe-csi.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spiffe-csi.fullname" . }}
      priorityClassName: system-node-critical
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: spiffe-csi-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--workload-api-socket-dir"
            - {{ .Values.spire.agentSocketDir | quote }}
            - "--plugin-name"
            - "csi.spiffe.io"
            - "--csi-socket-path"
            - "/spiffe-csi/csi.sock"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: spire-agent-socket-dir
              mountPath: {{ .Values.spire.agentSocketDir }}
              readOnly: true
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: spiffe-csi-socket-dir
              mountPath: /spiffe-csi
          securityContext:
            privileged: true   # CSI requires for bidirectional mountPropagation
        - name: node-driver-registrar
          image: "{{ .Values.nodeDriverRegistrarImage.repository }}:{{ .Values.nodeDriverRegistrarImage.tag }}"
          imagePullPolicy: {{ .Values.nodeDriverRegistrarImage.pullPolicy }}
          args:
            - "--csi-address=/spiffe-csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.spiffe.io/csi.sock"
          volumeMounts:
            - name: spiffe-csi-socket-dir
              mountPath: /spiffe-csi
            - name: kubelet-plugin-registration-dir
              mountPath: /registration
      volumes:
        - name: spire-agent-socket-dir
          hostPath:
            path: {{ .Values.spire.agentSocketDir }}
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: spiffe-csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.spiffe.io
            type: DirectoryOrCreate
        - name: kubelet-plugin-registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
{{- end }}
